added get/set-AtIndex methods for byte, boolean
openjdk/panama-foreign pull request #747
Opened 2022-10-22 10:17 UTC by RedIODev

This PR adds the left out getAtIndex and setAtIndex methods for byte and boolean to java.lang.foreign.MemorySegment.java

2022-10-22 10:22 UTC, RedIODev commented
/signed

2022-10-31 18:32 UTC, JornVernee reviewed
The changes look good but please amend the tests as well to test these new accessors. Looks like you can just add some test cases in `TestMemoryAccessInstance`.

2022-11-03 15:56 UTC, mcimadamore approved these changes
Looks good -thanks!

2023-02-08 17:29 UTC, JornVernee commented
Looks like this was never integrated.

@RedIODev Could you please type `/integrate` in order to integrate the PR.

2023-02-09 19:46 UTC, RedIODev commented
/integrate

2023-02-10 00:10 UTC, JornVernee requested changes
During some last minute testing it turned out there are some compilation failures after rebasing on the latest `foreign-memaccess+abi` branch, due to classes being renamed, and the javadoc still pointing to the old class name.

I've added the needed doc changes as inline suggestions. You should be able to easily apply them from GitHub.

Sorry about that.

2023-02-10 00:10 UTC, JornVernee commented on src/java.base/share/classes/java/lang/foreign/MemorySegment.java
> +     * the {@linkplain #session() session} associated with this segment.
```suggestion
     * @throws IllegalStateException if the {@linkplain #scope() scope} associated with this segment is not
     * {@linkplain SegmentScope#isAlive() alive}.
     * @throws WrongThreadException if this method is called from a thread {@code T},
     * such that {@code scope().isAccessibleBy(T) == false}.
```

2023-02-10 00:10 UTC, JornVernee commented on src/java.base/share/classes/java/lang/foreign/MemorySegment.java
> +     * the {@linkplain #session() session} associated with this segment.
```suggestion
     * @throws IllegalStateException if the {@linkplain #scope() scope} associated with this segment is not
     * {@linkplain SegmentScope#isAlive() alive}.
     * @throws WrongThreadException if this method is called from a thread {@code T},
     * such that {@code scope().isAccessibleBy(T) == false}.
```

2023-02-10 00:10 UTC, JornVernee commented on src/java.base/share/classes/java/lang/foreign/MemorySegment.java
> +     * the {@linkplain #session() session} associated with this segment.
```suggestion
     * @throws IllegalStateException if the {@linkplain #scope() scope} associated with this segment is not
     * {@linkplain SegmentScope#isAlive() alive}.
     * @throws WrongThreadException if this method is called from a thread {@code T},
     * such that {@code scope().isAccessibleBy(T) == false}.
```

2023-02-10 00:10 UTC, JornVernee commented on src/java.base/share/classes/java/lang/foreign/MemorySegment.java
> +     * the {@linkplain #session() session} associated with this segment.
```suggestion
     * @throws IllegalStateException if the {@linkplain #scope() scope} associated with this segment is not
     * {@linkplain SegmentScope#isAlive() alive}.
     * @throws WrongThreadException if this method is called from a thread {@code T},
     * such that {@code scope().isAccessibleBy(T) == false}.
```

2023-03-08 18:01 UTC, JornVernee commented
@RedIODev We've discussed this PR with the team, and we'd still like to take in this change. Apologies that the process has been a bit messy so far.

Do you want to take another look at this PR? (Unfortunately there are likely other changes needed on top of the ones I listed above, since the API has changed again). If not, we could also add these methods in a separate PR, if that seems more convenient.

2023-03-12 23:10 UTC, RedIODev commented
I think it's best if you wrap this up. I followed the api changes loosely but didn't keep up with all the details so I don't have the broader picture right now. I'm not sure what else needs to be changed on top of the requested changes. I would do it myself but I'm currently short on time and wouldn't be able to finish this for some time.

2023-03-13 13:52 UTC, closed without merging